import type { PresetBuild } from './types';

export const PRESET_BUILDS: PresetBuild[] = [
  {
    id: 'nd_msr_inspired', name: 'ND MSR-inspired',
    subtitle: 'Split lip, carbon steps and a blade spoiler', badge: 'New aero',
    description: 'A coordinated street build with the MSR-style split lip, side blades and stepped rear spoiler. These are original visual approximations inspired by real ND accessories.',
    config: {
      generation: 'nd', roofType: 'st', roofState: 'up', paint: 'soft_white',
      wheelStyle: 'rays_te37', wheelFinish: 'gloss_black', wheelDiameter: 17,
      rideHeight: -20, camber: -.8, trackOffset: 0,
      frontLip: 'msr_split_lip', sideSkirts: 'msr_side_blades', rearWing: 'msr_blade_spoiler',
      rearDiffuser: 'mp_street_diffuser', exhaust: 'oem_dual',
      environment: 'sunset', cameraPreset: 'exterior_360',
    },
  },
  {
    id: 'nd_club_aero', name: 'ND Club Aero',
    subtitle: 'Sculpted skirts, low wing and stacked canards', badge: 'New aero',
    description: 'A more assertive aero combination with a three-piece front lip, RS-style skirts, a low swan-neck wing, a street diffuser and rear spats.',
    config: {
      generation: 'nd', roofType: 'st', roofState: 'down', paint: 'zircon_sand',
      wheelStyle: 'enkei_rpf1', wheelFinish: 'satin_bronze', wheelDiameter: 17,
      rideHeight: -25, camber: -1.2, trackOffset: 0, wheelBrakes: true,
      frontLip: 'three_piece_lip', sideSkirts: 'rs_sculpted_skirts', rearWing: 'swan_neck_wing',
      rearDiffuser: 'mp_street_diffuser', exhaust: 'twin_oval', extraMods: ['FA22','RA26'],
      environment: 'warehouse', cameraPreset: 'exterior_360',
    },
  },
  {
    id: 'nd_street_kit',
    name: 'ND Street Kit',
    subtitle: 'Sculpted lip, slim skirts, low spoiler',
    badge: 'Street',
    description: 'Three coordinated ND accessories with a body-colour spoiler, satin-black lower blades and a mild 20 mm drop. Use Compare original aero to inspect the difference.',
    config: {
      generation: 'nd', roofType: 'st', roofState: 'up',
      paint: 'soul_red', wheelStyle: 'oem_17_design', wheelDiameter: 17,
      rideHeight: -20, camber: -0.5, trackOffset: 0,
      frontLip: 'club_lip', sideSkirts: 'oem_extensions', rearWing: 'oem_ducktail',
      environment: 'studio', cameraPreset: 'exterior_360',
    },
  },
  {
    id: 'club_spec',
    name: 'Soul Red Club',
    subtitle: 'Subtle street styling, top down',
    badge: 'Street',
    description:
      'Soul Red Crystal over the OEM 17" design wheels with a low body-colour boot spoiler and the roof down.',
    config: {
      generation: 'nd',
      roofType: 'st',
      roofState: 'down',
      paint: 'soul_red',
      wheelStyle: 'oem_17_design',
      wheelFinish: 'gloss_black',
      wheelDiameter: 17,
      caliperColor: 'brembo_red',
      rideHeight: 0,
      camber: -0.5,
      trackOffset: 0,
      frontLip: 'stock',
      rearWing: 'oem_ducktail',
      exhaust: 'stock_single',
      environment: 'studio',
    },
  },
  {
    id: 'rf_grand_tourer',
    name: 'Grand Tourer',
    subtitle: 'Machine Gray, roof up',
    badge: 'GT',
    description:
      'Machine Gray with the roof up, tan Nappa cabin, BBS mesh in hyper silver. Long-distance roadster.',
    config: {
      generation: 'nd',
      roofType: 'st',
      roofState: 'up',
      paint: 'machine_gray',
      interiorTrim: 'tan_nappa',
      wheelStyle: 'bbs_mesh',
      wheelFinish: 'hyper_silver',
      wheelDiameter: 17,
      caliperColor: 'powder_black',
      rideHeight: -15,
      camber: -0.8,
      trackOffset: 4,
      rearWing: 'oem_lip',
      exhaust: 'oem_dual',
      windowTint: 0.35,
      environment: 'sunset',
    },
  },
  {
    id: 'time_attack',
    name: 'Time Attack',
    subtitle: 'Full aero, coilovers, GT wing',
    badge: 'Track',
    description:
      'Carbon splitter, track diffuser and a GT wing over coilovers on Enkei RPF1s, with a bolt-in hoop.',
    config: {
      generation: 'nd',
      roofType: 'st',
      roofState: 'down',
      paint: 'arctic_white',
      wheelStyle: 'enkei_rpf1',
      wheelFinish: 'satin_bronze',
      wheelDiameter: 17,
      caliperColor: 'brembo_yellow',
      rideHeight: -55,
      camber: -3.2,
      trackOffset: 18,
      frontLip: 'aggressive_splitter',
      sideSkirts: 'carbon_extenders',
      rearDiffuser: 'track_diffuser',
      rearWing: 'gt_wing',
      hood: 'vented_carbon',
      exhaust: 'titanium_quad',
      rollBar: 'track_hoop',
      interiorTrim: 'red_alcantara',
      environment: 'warehouse',
      bloom: true,
    },
  },
  {
    id: 'shutoko_night',
    name: 'Shutoko Night',
    subtitle: 'Slammed, smoked, neon',
    badge: 'Street',
    description:
      'Midnight Purple over Watanabes, aired out on the deck with smoked indicators and tinted headlight housings.',
    config: {
      generation: 'nd',
      roofType: 'st',
      roofState: 'down',
      paint: 'midnight_purple',
      wheelStyle: 'watanabe_rs',
      wheelFinish: 'chrome',
      wheelDiameter: 17,
      caliperColor: 'polished',
      rideHeight: -85,
      camber: -4.5,
      trackOffset: 28,
      frontLip: 'club_lip',
      sideSkirts: 'oem_extensions',
      rearWing: 'oem_lip',
      exhaust: 'big_bore_single',
      smokedIndicators: true,
      tintedHeadlights: true,
      windowTint: 0.72,
      headlights: true,
      environment: 'urban_night',
      bloom: true,
      cameraPreset: 'front_low',
    },
  },
  {
    id: 'kyusha_tribute',
    name: 'Kyusha Tribute',
    subtitle: 'Classic Red on Watanabes',
    badge: 'Heritage',
    description:
      'A nod to the NA: Classic Red, tan roof, 15-inch Watanabe RS-8s and nothing else. Wing deleted, exhaust stock.',
    config: {
      generation: 'nd',
      roofType: 'st',
      roofState: 'up',
      roofFabric: 'tan',
      paint: 'classic_red',
      wheelStyle: 'watanabe_rs',
      wheelFinish: 'hyper_silver',
      wheelDiameter: 15,
      caliperColor: 'powder_black',
      rideHeight: -10,
      camber: -0.5,
      trackOffset: 6,
      frontLip: 'stock',
      rearWing: 'wing_delete',
      exhaust: 'stock_single',
      interiorTrim: 'tan_nappa',
      windowTint: 0,
      environment: 'salt_flats',
      bloom: false,
    },
  },
  {
    id: 'stealth_wrap',
    name: 'Satin Stealth',
    subtitle: 'Matte wrap, acid green details',
    badge: 'Wrap',
    description:
      'Satin Stealth Black wrap with acid green calipers, matte black RPF1s and a carbon lip. Bloom off, exposure down.',
    config: {
      generation: 'nd',
      roofType: 'st',
      roofState: 'up',
      paint: 'satin_stealth',
      wheelStyle: 'enkei_rpf1',
      wheelFinish: 'matte_black',
      wheelDiameter: 17,
      caliperColor: 'acid_green',
      rideHeight: -45,
      camber: -2.4,
      trackOffset: 16,
      frontLip: 'club_lip',
      sideSkirts: 'carbon_extenders',
      rearDiffuser: 'oem_diffuser',
      rearWing: 'oem_lip',
      hood: 'vented_carbon',
      exhaust: 'titanium_quad',
      windowTint: 0.62,
      smokedIndicators: true,
      environment: 'studio',
      exposure: 0.9,
    },
  },
];
