import type { PresetBuild } from './types';

export const PRESET_BUILDS: PresetBuild[] = [
  {
    id: 'club_spec',
    name: 'Soul Red Club',
    subtitle: 'Factory Club spec, top down',
    badge: 'OEM',
    description:
      'Soul Red Crystal over the OEM 17" design wheels, Brembo red calipers and the factory ducktail. Exactly how it leaves Hiroshima.',
    config: {
      generation: 'nd',
      roofType: 'st',
      roofState: 'down',
      paint: 'soul_red',
      wheelStyle: 'oem_17_design',
      wheelFinish: 'gloss_black',
      wheelDiameter: 17,
      caliperColor: 'brembo_red',
      rideHeight: 0,
      camber: -0.5,
      trackOffset: 0,
      frontLip: 'stock',
      rearWing: 'oem_ducktail',
      exhaust: 'stock_single',
      environment: 'studio',
    },
  },
  {
    id: 'rf_grand_tourer',
    name: 'RF Grand Tourer',
    subtitle: 'Machine Gray fastback',
    badge: 'RF',
    description:
      'Retractable Fastback roof up in Machine Gray, tan Nappa cabin, BBS mesh in hyper silver. Long-distance roadster.',
    config: {
      generation: 'nd',
      roofType: 'rf',
      roofState: 'up',
      paint: 'machine_gray',
      interiorTrim: 'tan_nappa',
      wheelStyle: 'bbs_mesh',
      wheelFinish: 'hyper_silver',
      wheelDiameter: 17,
      caliperColor: 'powder_black',
      rideHeight: -15,
      camber: -0.8,
      trackOffset: 4,
      rearWing: 'oem_lip',
      exhaust: 'oem_dual',
      windowTint: 0.35,
      environment: 'sunset',
    },
  },
  {
    id: 'time_attack',
    name: 'Time Attack',
    subtitle: 'Full aero, coilovers, GT wing',
    badge: 'Track',
    description:
      'Carbon splitter, track diffuser and a GT wing over coilovers on Enkei RPF1s. Recaro buckets and a bolt-in hoop.',
    config: {
      generation: 'nd',
      roofType: 'st',
      roofState: 'down',
      paint: 'arctic_white',
      wheelStyle: 'enkei_rpf1',
      wheelFinish: 'satin_bronze',
      wheelDiameter: 17,
      caliperColor: 'brembo_yellow',
      rideHeight: -55,
      camber: -3.2,
      trackOffset: 18,
      frontLip: 'aggressive_splitter',
      sideSkirts: 'carbon_extenders',
      rearDiffuser: 'track_diffuser',
      rearWing: 'gt_wing',
      hood: 'vented_carbon',
      exhaust: 'titanium_quad',
      rollBar: 'track_hoop',
      interiorTrim: 'recaro_bucket',
      environment: 'warehouse',
      bloom: true,
    },
  },
  {
    id: 'shutoko_night',
    name: 'Shutoko Night',
    subtitle: 'Slammed, smoked, neon',
    badge: 'Street',
    description:
      'Midnight Purple over Watanabes, aired out on the deck with smoked indicators and tinted headlight housings.',
    config: {
      generation: 'nd',
      roofType: 'rf',
      roofState: 'down',
      paint: 'midnight_purple',
      wheelStyle: 'watanabe_rs',
      wheelFinish: 'chrome',
      wheelDiameter: 17,
      caliperColor: 'polished',
      rideHeight: -85,
      camber: -4.5,
      trackOffset: 28,
      frontLip: 'club_lip',
      sideSkirts: 'oem_extensions',
      rearWing: 'oem_lip',
      exhaust: 'big_bore_single',
      smokedIndicators: true,
      tintedHeadlights: true,
      windowTint: 0.72,
      headlights: true,
      environment: 'urban_night',
      bloom: true,
      cameraPreset: 'front_low',
    },
  },
  {
    id: 'kyusha_tribute',
    name: 'Kyusha Tribute',
    subtitle: 'Classic Red on Watanabes',
    badge: 'Heritage',
    description:
      'A nod to the NA: Classic Red, tan roof, 15-inch Watanabe RS-8s and nothing else. Wing deleted, exhaust stock.',
    config: {
      generation: 'nd',
      roofType: 'st',
      roofState: 'up',
      roofFabric: 'tan',
      paint: 'classic_red',
      wheelStyle: 'watanabe_rs',
      wheelFinish: 'hyper_silver',
      wheelDiameter: 15,
      caliperColor: 'powder_black',
      rideHeight: -10,
      camber: -0.5,
      trackOffset: 6,
      frontLip: 'stock',
      rearWing: 'wing_delete',
      exhaust: 'stock_single',
      interiorTrim: 'tan_nappa',
      windowTint: 0,
      environment: 'salt_flats',
      bloom: false,
    },
  },
  {
    id: 'stealth_wrap',
    name: 'Satin Stealth',
    subtitle: 'Matte wrap, acid green details',
    badge: 'Wrap',
    description:
      'Satin Stealth Black wrap with acid green calipers, matte black RPF1s and a carbon lip. Bloom off, exposure down.',
    config: {
      generation: 'nd',
      roofType: 'rf',
      roofState: 'up',
      paint: 'satin_stealth',
      wheelStyle: 'enkei_rpf1',
      wheelFinish: 'matte_black',
      wheelDiameter: 17,
      caliperColor: 'acid_green',
      rideHeight: -45,
      camber: -2.4,
      trackOffset: 16,
      frontLip: 'club_lip',
      sideSkirts: 'carbon_extenders',
      rearDiffuser: 'oem_diffuser',
      rearWing: 'oem_lip',
      hood: 'vented_carbon',
      exhaust: 'titanium_quad',
      windowTint: 0.62,
      smokedIndicators: true,
      environment: 'studio',
      exposure: 0.9,
    },
  },
];
